"""Split RouterNet data at question level and standardize feature vectors.

This script reads router samples from JSONL, performs a deterministic question-level
split (train/val/test), fits StandardScaler on train features only, then writes
scaled JSONL files for each split.
"""

from __future__ import annotations

import argparse
import json
import random
from collections import defaultdict
from math import floor
from pathlib import Path
from typing import Iterable

import numpy as np
from sklearn.preprocessing import StandardScaler


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Split router_training_data.jsonl at question level with a "
            "train/val/test ratio and standardize feature vectors using "
            "StandardScaler fit on train split."
        )
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("RagRoute/router_training_data.jsonl"),
        help="Input JSONL path generated by fedrag/server_app.py",
    )
    parser.add_argument("--train-ratio", type=float, default=0.30)
    parser.add_argument("--val-ratio", type=float, default=0.10)
    parser.add_argument("--test-ratio", type=float, default=0.60)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--no-stratify-by-dataset",
        action="store_true",
        help="Disable per-dataset split; split all questions globally.",
    )
    return parser.parse_args()


def load_jsonl(path: Path) -> list[dict]:
    samples: list[dict] = []
    with path.open("r", encoding="utf-8") as infile:
        for line_number, line in enumerate(infile, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                samples.append(json.loads(line))
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON on line {line_number} in {path}: {exc}") from exc
    if not samples:
        raise ValueError(f"No samples found in {path}")
    return samples


def allocate_counts(n: int, ratios: tuple[float, float, float]) -> tuple[int, int, int]:
    raw = [n * ratio for ratio in ratios]
    base = [floor(value) for value in raw]
    remaining = n - sum(base)
    remainders = sorted(
        ((raw[idx] - base[idx], idx) for idx in range(len(raw))),
        reverse=True,
    )
    for _, idx in remainders[:remaining]:
        base[idx] += 1
    return int(base[0]), int(base[1]), int(base[2])


def split_ids(ids: list[str], ratios: tuple[float, float, float], rng: random.Random):
    ids = list(ids)
    rng.shuffle(ids)
    n_train, n_val, n_test = allocate_counts(len(ids), ratios)

    train_ids = set(ids[:n_train])
    val_ids = set(ids[n_train : n_train + n_val])
    test_ids = set(ids[n_train + n_val : n_train + n_val + n_test])
    return train_ids, val_ids, test_ids


def build_split_question_ids(
    samples: list[dict],
    ratios: tuple[float, float, float],
    seed: int,
    stratify_by_dataset: bool,
):
    qid_to_dataset: dict[str, str] = {}
    for sample in samples:
        qid = str(sample["question_id"])
        dataset = str(sample.get("dataset", "unknown"))
        if qid in qid_to_dataset and qid_to_dataset[qid] != dataset:
            raise ValueError(
                f"Question ID {qid} appears in multiple datasets: "
                f"{qid_to_dataset[qid]} and {dataset}."
            )
        qid_to_dataset[qid] = dataset

    rng = random.Random(seed)
    train_ids: set[str] = set()
    val_ids: set[str] = set()
    test_ids: set[str] = set()

    if stratify_by_dataset:
        dataset_to_qids: dict[str, list[str]] = defaultdict(list)
        for qid, dataset in qid_to_dataset.items():
            dataset_to_qids[dataset].append(qid)

        for dataset in sorted(dataset_to_qids):
            ds_rng = random.Random(rng.randint(0, 2**31 - 1))
            tr, va, te = split_ids(dataset_to_qids[dataset], ratios, ds_rng)
            train_ids.update(tr)
            val_ids.update(va)
            test_ids.update(te)
    else:
        tr, va, te = split_ids(list(qid_to_dataset), ratios, rng)
        train_ids.update(tr)
        val_ids.update(va)
        test_ids.update(te)

    if train_ids & val_ids or train_ids & test_ids or val_ids & test_ids:
        raise RuntimeError("Split overlap detected. Expected disjoint question ID sets.")

    return train_ids, val_ids, test_ids


def split_samples_by_question(
    samples: Iterable[dict], train_ids: set[str], val_ids: set[str], test_ids: set[str]
):
    train_samples: list[dict] = []
    val_samples: list[dict] = []
    test_samples: list[dict] = []

    for sample in samples:
        qid = str(sample["question_id"])
        if qid in train_ids:
            train_samples.append(sample)
        elif qid in val_ids:
            val_samples.append(sample)
        elif qid in test_ids:
            test_samples.append(sample)
        else:
            raise RuntimeError(f"Question ID {qid} was not assigned to any split.")

    return train_samples, val_samples, test_samples


def standardize_feature_vectors(
    train_samples: list[dict], val_samples: list[dict], test_samples: list[dict]
):
    def stack_features(rows: list[dict]) -> np.ndarray:
        return np.asarray([row["feature_vector"] for row in rows], dtype=np.float32)

    scaler = StandardScaler()
    train_features = stack_features(train_samples)
    scaler.fit(train_features)

    def transform(rows: list[dict]) -> list[dict]:
        features = stack_features(rows)
        scaled = scaler.transform(features)

        output_rows: list[dict] = []
        for row, feat in zip(rows, scaled):
            out = dict(row)
            out["feature_vector"] = feat.astype(np.float32).tolist()
            output_rows.append(out)
        return output_rows

    return transform(train_samples), transform(val_samples), transform(test_samples), scaler


def write_jsonl(path: Path, rows: list[dict]) -> None:
    with path.open("w", encoding="utf-8") as outfile:
        for row in rows:
            outfile.write(json.dumps(row, ensure_ascii=False) + "\n")


def count_questions(rows: list[dict]) -> int:
    return len({str(row["question_id"]) for row in rows})


def main() -> None:
    args = parse_args()
    ratios = (args.train_ratio, args.val_ratio, args.test_ratio)
    ratio_sum = sum(ratios)
    if abs(ratio_sum - 1.0) > 1e-9:
        raise ValueError(f"Ratios must sum to 1.0, got {ratio_sum}")

    input_path = args.input
    if not input_path.exists():
        raise FileNotFoundError(
            f"Input JSONL does not exist: {input_path}. Run 'flwr run .' first."
        )

    samples = load_jsonl(input_path)
    train_ids, val_ids, test_ids = build_split_question_ids(
        samples=samples,
        ratios=ratios,
        seed=args.seed,
        stratify_by_dataset=not args.no_stratify_by_dataset,
    )
    train_samples, val_samples, test_samples = split_samples_by_question(
        samples=samples,
        train_ids=train_ids,
        val_ids=val_ids,
        test_ids=test_ids,
    )
    train_scaled, val_scaled, test_scaled, scaler = standardize_feature_vectors(
        train_samples=train_samples,
        val_samples=val_samples,
        test_samples=test_samples,
    )

    base = input_path.with_suffix("")
    train_out = Path(f"{base}.train.jsonl")
    val_out = Path(f"{base}.val.jsonl")
    test_out = Path(f"{base}.test.jsonl")
    scaler_out = Path(f"{base}.scaler.npz")
    split_meta_out = Path(f"{base}.split_meta.json")

    write_jsonl(train_out, train_scaled)
    write_jsonl(val_out, val_scaled)
    write_jsonl(test_out, test_scaled)

    np.savez(
        scaler_out,
        mean=scaler.mean_.astype(np.float32),
        scale=scaler.scale_.astype(np.float32),
        var=scaler.var_.astype(np.float32),
        n_features_in=np.array([scaler.n_features_in_], dtype=np.int64),
    )

    split_meta = {
        "input": str(input_path),
        "ratios": {
            "train": args.train_ratio,
            "val": args.val_ratio,
            "test": args.test_ratio,
        },
        "seed": args.seed,
        "stratify_by_dataset": not args.no_stratify_by_dataset,
        "questions": {
            "train": len(train_ids),
            "val": len(val_ids),
            "test": len(test_ids),
            "total": len(train_ids) + len(val_ids) + len(test_ids),
        },
        "samples": {
            "train": len(train_scaled),
            "val": len(val_scaled),
            "test": len(test_scaled),
            "total": len(train_scaled) + len(val_scaled) + len(test_scaled),
        },
        "feature_dim": int(scaler.n_features_in_),
        "outputs": {
            "train_jsonl": str(train_out),
            "val_jsonl": str(val_out),
            "test_jsonl": str(test_out),
            "scaler_npz": str(scaler_out),
        },
    }

    split_meta_out.write_text(
        json.dumps(split_meta, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    print("Question-level split completed.")
    print(
        "Questions: "
        f"train={split_meta['questions']['train']}, "
        f"val={split_meta['questions']['val']}, "
        f"test={split_meta['questions']['test']}, "
        f"total={split_meta['questions']['total']}"
    )
    print(
        "Samples: "
        f"train={split_meta['samples']['train']}, "
        f"val={split_meta['samples']['val']}, "
        f"test={split_meta['samples']['test']}, "
        f"total={split_meta['samples']['total']}"
    )
    print(f"Train questions check via rows: {count_questions(train_scaled)}")
    print(f"Val questions check via rows: {count_questions(val_scaled)}")
    print(f"Test questions check via rows: {count_questions(test_scaled)}")
    print(f"Wrote: {train_out}")
    print(f"Wrote: {val_out}")
    print(f"Wrote: {test_out}")
    print(f"Wrote scaler: {scaler_out}")
    print(f"Wrote metadata: {split_meta_out}")


if __name__ == "__main__":
    main()
